# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-06 03:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True, verbose_name='Company Name')),
                ('phone_no', models.CharField(help_text='Include country code   00-91-PhoneNo', max_length=200, verbose_name='Contact No')),
                ('sales_partner', models.CharField(choices=[('SALESPARTNER', 'SALESPARTNER'), ('INDIVIDUAL', 'INDIVIDUAL')], help_text='Select Sales Partner, only  if your intrested in  becoming a  Sales partner', max_length=200, verbose_name='Sales Partner or Individual')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
