# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-06 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingbuddy', '0002_myprofile_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_region', models.CharField(choices=[('USA', 'USA'), ('GULF', 'GULF'), ('ASIA', 'ASIA'), ('EUROPE', 'EUROPE')], help_text='Select Region  Price is Applicable for ', max_length=200, verbose_name='Select Region')),
                ('plan', models.CharField(choices=[('INDIVIDUAL', 'INDIVIDUAL'), ('SILVER', 'SILVER'), ('GOLD', 'GOLD'), ('DIAMOND', 'DIAMOND')], help_text='Select Plan', max_length=200, verbose_name='Select Plan')),
                ('price', models.IntegerField(help_text='Enter Price', verbose_name='Enter Price')),
                ('currency', models.CharField(choices=[('USD', 'US DOLLARS'), ('INR', 'INDIAN RUPEES'), ('AED', 'DIRHAMS')], help_text='Select Currency', max_length=200, verbose_name='Select Currency')),
            ],
        ),
    ]
