# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-06 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingbuddy', '0003_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='target',
            field=models.CharField(choices=[('SALESPARTNER', 'SALESPARTNER'), ('INDIVIDUAL', 'INDIVIDUAL')], default=1, help_text='Select Type of User', max_length=200, verbose_name='Select User Type'),
            preserve_default=False,
        ),
    ]
