# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-07 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingbuddy', '0005_pricing_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='Company Name'),
        ),
    ]
