# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-07 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountingbuddy', '0006_auto_20170907_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(help_text='Enter the name of the business', max_length=200, verbose_name='Name of Business Required')),
                ('business_type', models.CharField(choices=[('SERVICE', 'SERVICES'), ('MANUFACTURING', 'MANUFACTURING'), ('SALES', 'SALES'), ('PERSONAL', 'PERSONAL'), ('SOCIETY', 'SOCIETY'), ('SCHOOL', 'SCHOOL'), ('SUPER MARKER', 'SUPER MARKET')], help_text='If your business type is not present,enter in additional details and select the closest type here', max_length=200, verbose_name='Select Business Type')),
                ('additional_details', models.CharField(blank=True, max_length=200, verbose_name='Enter any additional details')),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountingbuddy.Pricing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
