# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-09 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingbuddy', '0007_business_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_request',
            name='pay_slip',
            field=models.FileField(blank=True, null=True, upload_to='budinessReqForm'),
        ),
        migrations.AddField(
            model_name='business_request',
            name='purchase_invoice',
            field=models.FileField(blank=True, null=True, upload_to='budinessReqForm'),
        ),
        migrations.AddField(
            model_name='business_request',
            name='sales_invoice',
            field=models.FileField(blank=True, null=True, upload_to='businessReqForm'),
        ),
        migrations.AddField(
            model_name='business_request',
            name='talley_file',
            field=models.FileField(blank=True, null=True, upload_to='budinessReqForm'),
        ),
        migrations.AddField(
            model_name='business_request',
            name='tax_structure',
            field=models.CharField(blank=True, help_text='Describe your Tax Structure', max_length=200, verbose_name='Tax Structure'),
        ),
    ]
