# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-10 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingbuddy', '0008_auto_20170909_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_request',
            name='pay_slip',
            field=models.FileField(blank=True, null=True, upload_to='businessReqForm'),
        ),
        migrations.AlterField(
            model_name='business_request',
            name='purchase_invoice',
            field=models.FileField(blank=True, null=True, upload_to='businessReqForm'),
        ),
        migrations.AlterField(
            model_name='business_request',
            name='talley_file',
            field=models.FileField(blank=True, null=True, upload_to='businessReqForm'),
        ),
    ]
