# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-10 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingbuddy', '0009_auto_20170910_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(help_text='Emails of Business Request Will be Sent To', max_length=254, verbose_name='Email Address')),
            ],
        ),
    ]
